name: _error
timestamp: 1605151215
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1605151215
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-7355: Logo
  spacer:
    spacer-2452: Spacer
    spacer-8500: Spacer
  menu:
    menu-5501: Menu
  content:
    system-content-8542: 'Page Content'
  position:
    position-footer: Footer
  copyright:
    copyright-4523: Copyright
  branding:
    branding-1623: Branding
  mobile-menu:
    mobile-menu-2324: Mobile-menu
inherit: {  }
