version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: _error
  timestamp: 1605151215
layout:
  /header/:
    -
      - 'logo-7355 30'
      - 'spacer-2452 70'
  /navigation/:
    -
      - menu-5501
  /main/:
    -
      - system-content-8542
  /footer/:
    -
      - position-footer
    -
      - 'copyright-4523 40'
      - 'spacer-8500 30'
      - 'branding-1623 30'
  offcanvas:
    -
      - mobile-menu-2324
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-footer:
    attributes:
      key: footer
