atoms:
  -
    id: assets-5842
    type: assets
    title: 'Custom CSS / JS'
    inherit:
      outline: default
      atom: assets-5842
      include:
        - attributes
  -
    title: 'Google Analytics'
    type: analytics
    id: analytics-8341
    inherit:
      outline: default
      atom: analytics-8341
      include:
        - attributes
  -
    id: assets-9950
    type: assets
    title: 'Custom CSS / JS'
    attributes:
      enabled: '1'
      css:
        - { location: '', inline: ".g-home-particles.g-helium-style #g-intro {\nposition:relative;\n}\n\n.g-home-particles.g-helium-style #g-intro .g-container {\nposition: absolute;\nbottom:-300%;\nz-index:30;\n}\n\n.call-to-action-form {\npadding:20px !important;\nbackground-color: rgba(255,255,255,0.6);\n}\n\n\n@media (max-width: 700px) {\n  .g-home-particles.g-helium-style #g-intro .g-container {\n    position: static;\n    bottom:0;\n     z-index:1;\n   }\n}", extra: {  }, priority: '0', name: 'Custom Home' }
      javascript: {  }
