version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: home_-_particles
  timestamp: 1605151307
layout:
  navigation: {  }
  /header/:
    -
      - owlcarousel-2455
  /intro/:
    -
      - 'custom-5728 50'
      - 'position-module-5586 50'
    -
      - gp_calltoaction4-1795
  /features/:
    -
      - custom-3119
  /utility/: {  }
  /above/:
    -
      - contentcubes-7850
  /testimonials/:
    -
      - custom-7658
  /expanded/:
    -
      - custom-6355
  /container-main/:
    -
      -
        'mainbar 75': {  }
      -
        'sidebar 25': {  }
  footer: {  }
  offcanvas: {  }
structure:
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  header:
    attributes:
      boxed: ''
      class: g-flushed
      variations: ''
  intro:
    type: section
    attributes:
      boxed: ''
  features:
    type: section
    attributes:
      boxed: ''
  utility:
    type: section
    attributes:
      boxed: ''
      class: ''
  above:
    type: section
    attributes:
      boxed: ''
  testimonials:
    type: section
    attributes:
      boxed: ''
  expanded:
    type: section
    attributes:
      boxed: ''
  mainbar:
    type: section
    subtype: main
  sidebar:
    type: section
    subtype: aside
  container-main:
    attributes:
      boxed: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  owlcarousel-2455:
    title: 'Banner Principal'
    attributes:
      nav: disable
      dots: disable
      autoplay: enable
      autoplaySpeed: '7000'
      imageOverlay: enable
      items:
        -
          class: ''
          image: 'gantry-media://header/tokoko-ecotravel-manaure.jpg'
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttonclass: ''
          disable: '0'
          name: 'Quiénes somos'
        -
          class: ''
          image: 'gantry-media://header/sal-manaure-tokoko-ecotravel.jpg'
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttonclass: ''
          disable: '0'
          name: 'Planes Turísticos'
        -
          class: ''
          image: 'gantry-media://header/tokoko-ecotravel-3.jpg'
          title: ''
          desc: ''
          link: ''
          linktext: ''
          buttonclass: ''
          disable: '0'
          name: Blog
  custom-5728:
    title: 'Lead Text'
    attributes:
      html: "<h1 class=\"mb-0\">Tokoko EcoTravel <br/>\n</h1>\n<h3>\n<em> ¡Un viaje ecológicamente guiado!</em>\n</h3>\n\n"
    block:
      class: 'text-white d-flex flex-column justify-content-center pl-5'
      fixed: '1'
  position-module-5586:
    title: 'Call To Action'
    attributes:
      module_id: '91'
      key: call-to-action
  gp_calltoaction4-1795:
    title: 'Quiénes Somos Enlace Call To Action'
    attributes:
      class: ''
      bg_color: '#f5f7fa'
      text_color: '#636363'
      border_color: '#dddddd'
      border_left_color: ''
      bg_img: ''
      bg_mask_color: '#000000'
      bg_mask: ''
      padding: 50px
      shadow: ''
      font_size: ''
      title: 'TOKOKO ECOTRAVEL ESTÁ AQUÍ'
      title_tag: h3
      desc: 'Conoce todo sobre la agencia de turismo ecológicamente responsable que opera en la Alta Guajira colombiana. '
      button_text: 'Quiénes Somos'
      button_url: 'http://tokokoecotravel.com/quienes-somos'
      button_class: 'ui button yellow medium'
      button_target: _self
    block:
      class: 'mt-5 mb-5 ml-5'
  custom-3119:
    title: Features
    attributes:
      html: "<div class=\"fp-features\">\n    <div class=\"g-grid\">\n        <div class=\"g-block size-33-3\">\n            <div class=\"card\">\n                <div class=\"card-block\">\n                    <i class=\"fa fa-joomla\"></i>\n                    <h4 class=\"card-title\">Joomla</h4>\n                    <p class=\"card-text\">Bring your website to life with one of the most powerful and popular theming frameworks for Joomla.</p>\n                </div>\n            </div>\n        </div>\n        <div class=\"g-block size-33-3\">\n            <div class=\"card\">\n                <div class=\"card-block\">\n                    <i class=\"fa fa-wordpress\"></i>\n                    <h4 class=\"card-title\">WordPress</h4>\n                    <p class=\"card-text\">Gantry extends WordPress' native functionality, empowering users to manipulate virtually every aspect of their visitors' experience.</p>\n                </div>\n            </div>\n        </div>\n        <div class=\"g-block size-33-3\">\n            <div class=\"card\">\n                <div class=\"card-block\">\n                    <i class=\"fa fa-grav\"></i>\n                    <h4 class=\"card-title\">Grav</h4>\n                    <p class=\"card-text\">Gantry 5 is the first theming framework for Grav, designed by members of the same team that developed the CMS.</p>\n                </div>\n            </div>\n        </div>\n    </div>\n</div>"
    block:
      variations: center
  contentcubes-7850:
    title: 'Content Cubes'
    attributes:
      items:
        -
          image: 'gantry-media://above/img01.jpeg'
          imageposition: left
          label: Featured
          title: 'Gantry 5 Won "Best Framework System" at J and Beyond 2016 '
          tags:
            -
              icon: 'fa fa-tag'
              link: '#'
              target: _self
              text: 'Design Studio'
            -
              icon: 'fa fa-tag'
              link: '#'
              target: _self
              text: Photo
          link: 'http://gantry.org/blog/gantry5-wins-joscar'
          linktext: '&rarr;'
          buttonclass: ''
          buttontarget: _self
          name: 'Item 1'
        -
          image: 'gantry-media://above/img02.jpeg'
          imageposition: right
          label: Featured
          title: 'Gantry 5 Has Been Downloaded Over Half a Million Times'
          tags:
            -
              icon: 'fa fa-tag'
              link: '#'
              target: _self
              text: 'Graphic Design'
            -
              icon: 'fa fa-tag'
              link: '#'
              target: _self
              text: 'Website Creation'
          link: 'http://gantry.org'
          linktext: '&rarr;'
          buttonclass: ''
          buttontarget: _self
          name: 'Item 2'
  custom-7658:
    title: 'Customer Testimonials'
    attributes:
      html: "<div class=\"fp-testimonials\">\n    <blockquote>\n        <img src=\"gantry-media://testimonials/face.jpg\" alt=\"Avatar\" class=\"g-img-circle\" height=\"80\" width=\"80\">\n        <p class=\"h3\">\"Helium is a beautiful, free theme made by the RocketTheme team in appreciation of the incredible Gantry community.\"</p>\n        <footer>Andy Miller</footer>\n    </blockquote>\n</div>"
    block:
      variations: center
  custom-6355:
    title: 'Develop CMS themes quickly'
    attributes:
      html: "<div class=\"fp-multi-column-text\">\n    <h2 class=\"g-title\">Develop CMS themes quickly and efficiently</h2>\n    <div class=\"g-grid\">\n        <div class=\"g-block size-50\">\n            <p>\n                Helium was crafted with love by the <a href=\"http://rockettheme.com\">RocketTheme</a> team to showcase the capabilities of the Gantry 5 framework. Helium is open source and available for free under a dual license system (<a href=\"http://www.opensource.org/licenses/mit-license.php\">MIT</a> or <a href=\"http://www.gnu.org/licenses/old-licenses/gpl-2.0.html\">GPL version 2 or later</a>). You do not have to keep the Gantry or RocketTheme links and logos in the front end, however, you must ensure that all copyright notices in the code are retained.\n            </p>\n        </div>\n        <div class=\"g-block size-50\">\n            <p>\n                Documentation for Gantry 5 is available on the <a href=\"http://docs.gantry.org\">official Gantry website</a>. You can submit any issues or feature requests for Gantry through <a href=\"http://github.com/gantry/gantry5\">GitHub</a>. A chat room has been set up using <a href=\"https://gitter.im/gantry/gantry5\">Gitter</a> where you can go to talk about the project with developers, contributors, and other members of the community. This is the best place to go to get quick tips and discuss features with others.\n            </p>\n        </div>\n    </div>\n</div>"
    block:
      variations: title-center
