name: _body_only
timestamp: 1605151215
version: 7
preset:
  image: 'gantry-admin://images/layouts/body-only.png'
  name: _body_only
  timestamp: 1605151215
positions: {  }
sections:
  main: Main
particles:
  messages:
    system-messages-6727: 'System Messages'
  content:
    system-content-9926: 'Page Content'
inherit: {  }
